export type Country = "USA" | "Hong Kong" | "Kazakhstan" | "Europe";

export type University = {
  id: string;
  name: string;
  country: Country;
  city: string;
  qs: number;
  gpa: string;
  sat?: string;
  act?: string;
  ap?: string;
  unt?: string;
  nuet?: string;
  english: string;
  aid: string;
  tuition: string;
  deadlines: { label: string; date: string }[];
  programs: string[];
  overview: string;
  strategy: string;
  photos: string[];
};

const POOL = [
  "photo-1562774053-701939374585",
  "photo-1523050854058-8df90110c9f1",
  "photo-1498243691581-b145c3f54a5a",
  "photo-1541339907198-e08756dedf3f",
  "photo-1592280771190-3e2e4d571952",
  "photo-1607237138185-eedd9c632b0b",
  "photo-1580582932707-520aed937b7b",
  "photo-1519452575417-564c1401ecc0",
  "photo-1567168544813-cc03465b4fa8",
  "photo-1568792923760-d70635a89fdc",
  "photo-1590012314607-cda9d9b699ae",
  "photo-1591123120675-6f7f1aae0e5b",
];

function photos(seed: number) {
  return [0, 1, 2].map(
    (i) =>
      `https://images.unsplash.com/${POOL[(seed * 3 + i) % POOL.length]}?auto=format&fit=crop&w=900&q=70`,
  );
}

type Raw = Omit<University, "photos" | "id"> & { id?: string };

const RAW: Raw[] = [
  // ============ USA — Top 20 ============
  {
    name: "Massachusetts Institute of Technology",
    country: "USA",
    city: "Cambridge, MA",
    qs: 1,
    gpa: "3.95+ (UW)",
    sat: "1520–1580",
    act: "34–36",
    ap: "8+ AP, баллы 5",
    english: "TOEFL 100+ / IELTS 7.5",
    aid: "Need-blind для всех, 100% покрытие потребности",
    tuition: "~$85 000 / год (до вычета помощи)",
    deadlines: [
      { label: "Early Action", date: "2026-11-01" },
      { label: "Regular Decision", date: "2027-01-05" },
    ],
    programs: ["Computer Science", "EECS", "Physics", "Mechanical Engineering"],
    overview:
      "Инженерный и научный центр мира. Культура hands-on проектов, UROP-исследования с первого курса, мощная стартап-экосистема Kendall Square.",
    strategy:
      "Нужны исследовательские или инженерные проекты национального уровня: олимпиады IMO/IPhO, публикации, собственные устройства или open-source. Эссе — про мышление, а не про титулы.",
  },
  {
    name: "Stanford University",
    country: "USA",
    city: "Stanford, CA",
    qs: 6,
    gpa: "3.95+ (UW)",
    sat: "1500–1570",
    act: "34–36",
    ap: "7+ AP, баллы 4–5",
    english: "TOEFL 100+ / IELTS 7.0",
    aid: "Need-based, бесплатно при доходе семьи < $100k",
    tuition: "~$82 000 / год",
    deadlines: [
      { label: "Restrictive Early Action", date: "2026-11-01" },
      { label: "Regular Decision", date: "2027-01-05" },
    ],
    programs: ["Computer Science", "Symbolic Systems", "Bioengineering", "Economics"],
    overview:
      "Кампус в Кремниевой долине, сильнейшая предпринимательская среда, гибкий учебный план и междисциплинарность.",
    strategy:
      "Stanford ищет «интеллектуальную живость». Покажите нестандартный проект и активность, которую вы создали сами, а не просто посещали.",
  },
  {
    name: "Harvard University",
    country: "USA",
    city: "Cambridge, MA",
    qs: 4,
    gpa: "3.95+ (UW)",
    sat: "1500–1580",
    act: "34–36",
    ap: "8+ AP",
    english: "TOEFL 100+ / IELTS 7.5",
    aid: "Need-blind для международных, 100% потребности",
    tuition: "~$83 000 / год",
    deadlines: [
      { label: "Early Action", date: "2026-11-01" },
      { label: "Regular Decision", date: "2027-01-01" },
    ],
    programs: ["Economics", "Government", "Applied Math", "Molecular Biology"],
    overview:
      "Классический Ivy League: house-система, огромные ресурсы библиотек и лабораторий, сильнейший alumni-нетворк.",
    strategy:
      "Решают рекомендации и нарратив. Нужен «шпиль» — одна область, где вы лучший из тысяч, плюс сильная гуманитарная письменная работа.",
  },
  {
    name: "California Institute of Technology",
    country: "USA",
    city: "Pasadena, CA",
    qs: 10,
    gpa: "4.0 (UW)",
    sat: "1530–1580",
    act: "35–36",
    ap: "AP Calculus BC, Physics C, Chemistry — 5",
    english: "TOEFL 100+",
    aid: "Need-based, ограниченно для международных",
    tuition: "~$80 000 / год",
    deadlines: [
      { label: "Early Action", date: "2026-11-01" },
      { label: "Regular Decision", date: "2027-01-03" },
    ],
    programs: ["Physics", "Astrophysics", "Chemical Engineering", "CS"],
    overview:
      "Самый маленький топ-вуз США (~1000 бакалавров) с экстремальной академической нагрузкой и доступом к JPL/NASA.",
    strategy:
      "Только глубокая математика и физика. Олимпиадные медали и исследования обязательны, широта активностей вторична.",
  },
  {
    name: "Princeton University",
    country: "USA",
    city: "Princeton, NJ",
    qs: 22,
    gpa: "3.95+",
    sat: "1510–1570",
    act: "34–36",
    ap: "7+ AP",
    english: "TOEFL 100+ / IELTS 7.5",
    aid: "Need-blind, самая щедрая помощь в Ivy",
    tuition: "~$82 000 / год",
    deadlines: [
      { label: "Single-Choice Early Action", date: "2026-11-01" },
      { label: "Regular Decision", date: "2027-01-01" },
    ],
    programs: ["Operations Research", "Public Policy", "Physics", "Computer Science"],
    overview:
      "Фокус на бакалавриате: senior thesis у каждого, маленькие семинары, огромный эндаумент на студента.",
    strategy: "Ценится интеллектуальная самостоятельность и исследовательский опыт со школы.",
  },
  {
    name: "Yale University",
    country: "USA",
    city: "New Haven, CT",
    qs: 23,
    gpa: "3.95+",
    sat: "1500–1560",
    act: "33–35",
    ap: "7+ AP",
    english: "TOEFL 100+ / IELTS 7.0",
    aid: "Need-blind для международных",
    tuition: "~$85 000 / год",
    deadlines: [
      { label: "Early Action", date: "2026-11-01" },
      { label: "Regular Decision", date: "2027-01-02" },
    ],
    programs: ["Political Science", "Economics", "History", "Global Affairs"],
    overview:
      "Сильнейшие гуманитарные и социальные науки, residential colleges, огромное количество студенческих организаций.",
    strategy: "Yale любит «общественников»: лидерство, дебаты, MUN, социальные проекты.",
  },
  {
    name: "University of Pennsylvania",
    country: "USA",
    city: "Philadelphia, PA",
    qs: 11,
    gpa: "3.9+",
    sat: "1500–1560",
    act: "34–35",
    ap: "6+ AP",
    english: "TOEFL 100+ / IELTS 7.0",
    aid: "Need-aware для международных",
    tuition: "~$87 000 / год",
    deadlines: [
      { label: "Early Decision", date: "2026-11-01" },
      { label: "Regular Decision", date: "2027-01-05" },
    ],
    programs: ["Wharton Business", "Bioengineering", "Nursing", "Cognitive Science"],
    overview: "Wharton — лучшая бизнес-школа бакалавриата, сильные междисциплинарные программы.",
    strategy:
      "ED даёт максимальный прирост шансов. Нужен конкретный «why Penn» и бизнес/исследовательский трек.",
  },
  {
    name: "Cornell University",
    country: "USA",
    city: "Ithaca, NY",
    qs: 16,
    gpa: "3.85+",
    sat: "1470–1550",
    act: "33–35",
    ap: "6+ AP",
    english: "TOEFL 100+ / IELTS 7.0",
    aid: "Need-aware для международных",
    tuition: "~$88 000 / год",
    deadlines: [
      { label: "Early Decision", date: "2026-11-01" },
      { label: "Regular Decision", date: "2027-01-02" },
    ],
    programs: ["Engineering", "Hotel Administration", "CALS", "Architecture"],
    overview: "Самый большой Ivy с 7 колледжами; выбор колледжа сильно влияет на шансы.",
    strategy: "Подавайтесь в менее конкурентный колледж, соответствующий вашему профилю.",
  },
  {
    name: "Columbia University",
    country: "USA",
    city: "New York, NY",
    qs: 34,
    gpa: "3.9+",
    sat: "1500–1560",
    act: "34–35",
    ap: "7+ AP",
    english: "TOEFL 105+ / IELTS 7.5",
    aid: "Need-blind для всех",
    tuition: "~$90 000 / год",
    deadlines: [
      { label: "Early Decision", date: "2026-11-01" },
      { label: "Regular Decision", date: "2027-01-01" },
    ],
    programs: ["Core Curriculum", "Financial Economics", "Data Science", "Journalism"],
    overview: "Манхэттен, Core Curriculum, стажировки в финансах и медиа прямо во время учёбы.",
    strategy: "Сильные эссе про книги и город. Ищут широкую эрудицию.",
  },
  {
    name: "University of Chicago",
    country: "USA",
    city: "Chicago, IL",
    qs: 21,
    gpa: "3.9+",
    sat: "1510–1570",
    act: "34–35",
    ap: "6+ AP",
    english: "TOEFL 100+ / IELTS 7.0",
    aid: "Щедрая need-based помощь, есть merit-стипендии",
    tuition: "~$88 000 / год",
    deadlines: [
      { label: "Early Action / ED I", date: "2026-11-01" },
      { label: "ED II / Regular", date: "2027-01-05" },
    ],
    programs: ["Economics", "Mathematics", "Public Policy", "Statistics"],
    overview: "Интеллектуальный тяжеловес: Core, экономика чикагской школы, культура дискуссии.",
    strategy: "Знаменитые нестандартные эссе — шанс выделиться без идеальных баллов.",
  },
  {
    name: "Johns Hopkins University",
    country: "USA",
    city: "Baltimore, MD",
    qs: 28,
    gpa: "3.9+",
    sat: "1510–1560",
    act: "34–35",
    ap: "6+ AP, включая Biology/Chemistry",
    english: "TOEFL 100+ / IELTS 7.0",
    aid: "Need-based, ограниченно для международных",
    tuition: "~$86 000 / год",
    deadlines: [
      { label: "Early Decision I", date: "2026-11-01" },
      { label: "Regular Decision", date: "2027-01-02" },
    ],
    programs: ["Biomedical Engineering", "Public Health", "Neuroscience", "International Studies"],
    overview: "Мировой центр биомедицины и медицинских исследований.",
    strategy: "Лабораторный или больничный волонтёрский опыт заметно усиливает заявку.",
  },
  {
    name: "University of California, Berkeley",
    country: "USA",
    city: "Berkeley, CA",
    qs: 12,
    gpa: "3.9+ (UC GPA 4.2+)",
    sat: "не учитывается",
    act: "не учитывается",
    ap: "8+ AP для UC GPA",
    english: "TOEFL 80+ / IELTS 6.5",
    aid: "Международным помощь почти не даётся",
    tuition: "~$68 000 / год",
    deadlines: [{ label: "UC Application", date: "2026-11-30" }],
    programs: ["EECS", "Data Science", "Business (Haas)", "Molecular Biology"],
    overview: "Публичный топ №1, гигантский выбор курсов и близость к Кремниевой долине.",
    strategy: "Test-blind: решают AP, GPA и 4 Personal Insight Questions.",
  },
  {
    name: "UCLA",
    country: "USA",
    city: "Los Angeles, CA",
    qs: 42,
    gpa: "3.9+",
    sat: "не учитывается",
    act: "не учитывается",
    ap: "7+ AP",
    english: "TOEFL 87+ / IELTS 7.0",
    aid: "Крайне ограниченная для международных",
    tuition: "~$66 000 / год",
    deadlines: [{ label: "UC Application", date: "2026-11-30" }],
    programs: ["Computer Science", "Film & TV", "Psychology", "Economics"],
    overview: "Самый популярный вуз США по числу заявок; сильны и STEM, и креативные индустрии.",
    strategy: "Покажите долгосрочную вовлечённость и влияние на сообщество.",
  },
  {
    name: "University of Michigan–Ann Arbor",
    country: "USA",
    city: "Ann Arbor, MI",
    qs: 44,
    gpa: "3.85+",
    sat: "1380–1520",
    act: "32–34",
    ap: "5+ AP",
    english: "TOEFL 100+ / IELTS 7.0",
    aid: "Ограниченная, есть merit-стипендии",
    tuition: "~$70 000 / год",
    deadlines: [
      { label: "Early Action", date: "2026-11-01" },
      { label: "Regular Decision", date: "2027-02-01" },
    ],
    programs: ["Engineering", "Ross Business", "Kinesiology", "Information"],
    overview: "Мощный исследовательский публичный университет с огромным студенческим сообществом.",
    strategy: "Ранняя подача сильно помогает; важна конкретика в «why school» эссе.",
  },
  {
    name: "Carnegie Mellon University",
    country: "USA",
    city: "Pittsburgh, PA",
    qs: 58,
    gpa: "3.9+",
    sat: "1500–1560",
    act: "34–35",
    ap: "Calculus BC, CS A — 5",
    english: "TOEFL 102+ / IELTS 7.5",
    aid: "Need-aware, немного merit",
    tuition: "~$85 000 / год",
    deadlines: [
      { label: "Early Decision I", date: "2026-11-01" },
      { label: "Regular Decision", date: "2027-01-03" },
    ],
    programs: ["School of Computer Science", "Robotics", "Drama", "Design"],
    overview: "SCS — сильнейшая CS-школа мира вместе с MIT/Stanford; уникальный микс тех + арт.",
    strategy: "Портфолио кода/робототехники и олимпиады по информатике решают всё.",
  },
  {
    name: "Duke University",
    country: "USA",
    city: "Durham, NC",
    qs: 51,
    gpa: "3.95+",
    sat: "1510–1570",
    act: "34–35",
    ap: "6+ AP",
    english: "TOEFL 100+ / IELTS 7.0",
    aid: "Need-based, полное покрытие для принятых",
    tuition: "~$87 000 / год",
    deadlines: [
      { label: "Early Decision", date: "2026-11-01" },
      { label: "Regular Decision", date: "2027-01-02" },
    ],
    programs: ["Public Policy", "Biomedical Engineering", "Economics", "Global Health"],
    overview: "Баланс исследований, спорта и сильного комьюнити; кампус Gothic Wonderland.",
    strategy: "ED повышает шансы почти вдвое. Ценят служение сообществу.",
  },
  {
    name: "Northwestern University",
    country: "USA",
    city: "Evanston, IL",
    qs: 50,
    gpa: "3.9+",
    sat: "1490–1560",
    act: "34–35",
    ap: "6+ AP",
    english: "TOEFL 105+ / IELTS 7.5",
    aid: "Need-blind для международных",
    tuition: "~$88 000 / год",
    deadlines: [
      { label: "Early Decision", date: "2026-11-01" },
      { label: "Regular Decision", date: "2027-01-03" },
    ],
    programs: ["Journalism (Medill)", "Industrial Engineering", "Theatre", "Economics"],
    overview: "Квартальная система, сильная журналистика и коммуникации, кампус у озера Мичиган.",
    strategy: "Ищут «фит» с конкретной школой внутри университета.",
  },
  {
    name: "New York University",
    country: "USA",
    city: "New York, NY",
    qs: 43,
    gpa: "3.7+",
    sat: "1450–1560",
    act: "33–35",
    ap: "5+ AP",
    english: "TOEFL 100+ / IELTS 7.5",
    aid: "Ограниченная, есть merit-стипендии",
    tuition: "~$90 000 / год",
    deadlines: [
      { label: "Early Decision I", date: "2026-11-01" },
      { label: "Regular Decision", date: "2027-01-05" },
    ],
    programs: ["Stern Business", "Tisch Arts", "Computer Science", "Politics"],
    overview: "Город как кампус, глобальная сеть (Abu Dhabi, Shanghai), сильный бизнес и искусство.",
    strategy: "Гибкие требования по тестам: можно заменить SAT тремя AP с баллом 4–5.",
  },
  {
    name: "University of Illinois Urbana-Champaign",
    country: "USA",
    city: "Urbana, IL",
    qs: 69,
    gpa: "3.7+",
    sat: "1400–1520",
    act: "31–34",
    ap: "5+ AP",
    english: "TOEFL 100+ / IELTS 6.5",
    aid: "Merit-стипендии для международных",
    tuition: "~$56 000 / год",
    deadlines: [
      { label: "Early Action", date: "2026-11-01" },
      { label: "Regular Decision", date: "2027-01-05" },
    ],
    programs: ["Computer Science", "Electrical Engineering", "Accounting", "Agriculture"],
    overview: "Одна из лучших инженерных школ США при заметно более низкой стоимости.",
    strategy: "Отличный Match-вариант для сильного STEM-профиля с ограниченным бюджетом.",
  },
  {
    name: "Georgia Institute of Technology",
    country: "USA",
    city: "Atlanta, GA",
    qs: 83,
    gpa: "3.8+",
    sat: "1420–1540",
    act: "32–35",
    ap: "6+ AP STEM",
    english: "TOEFL 90+ / IELTS 7.0",
    aid: "Очень ограниченная для международных",
    tuition: "~$52 000 / год",
    deadlines: [
      { label: "Early Action II", date: "2026-11-02" },
      { label: "Regular Decision", date: "2027-01-04" },
    ],
    programs: ["Computer Science", "Aerospace", "Industrial Engineering", "Cybersecurity"],
    overview: "Лучшее соотношение цена/качество среди инженерных вузов США, co-op программы.",
    strategy: "Практические проекты и стажировки важнее, чем широкий список клубов.",
  },

  // ============ Hong Kong ============
  {
    name: "University of Hong Kong (HKU)",
    country: "Hong Kong",
    city: "Pokfulam",
    qs: 17,
    gpa: "3.7+",
    sat: "1400+",
    act: "31+",
    ap: "3–4 AP с баллами 4–5",
    english: "IELTS 6.5 / TOEFL 93",
    aid: "Entrance Scholarships до полной стоимости",
    tuition: "HK$182 000 / год",
    deadlines: [
      { label: "Main Round", date: "2026-11-15" },
      { label: "Final Deadline", date: "2027-05-30" },
    ],
    programs: ["Medicine", "Law", "Business & Finance", "Computer Science"],
    overview: "Старейший и самый престижный вуз Гонконга, обучение на английском.",
    strategy: "Количественный отбор: AP-баллы и IELTS решают. Подавайтесь в главном раунде.",
  },
  {
    name: "Hong Kong University of Science and Technology",
    country: "Hong Kong",
    city: "Clear Water Bay",
    qs: 47,
    gpa: "3.7+",
    sat: "1400+",
    act: "31+",
    ap: "Calculus BC + Physics/CS, баллы 5",
    english: "IELTS 6.5 / TOEFL 90",
    aid: "HKUST Scholarship Scheme (до full ride)",
    tuition: "HK$180 000 / год",
    deadlines: [
      { label: "Early Round", date: "2026-11-05" },
      { label: "Regular Round", date: "2027-01-10" },
    ],
    programs: ["Engineering", "Quantitative Finance", "Data Science", "Business"],
    overview: "Молодой технологический вуз с сильнейшей в Азии бизнес-школой.",
    strategy: "Сильная математика и олимпиадные результаты дают шанс на полную стипендию.",
  },
  {
    name: "Chinese University of Hong Kong (CUHK)",
    country: "Hong Kong",
    city: "Sha Tin",
    qs: 36,
    gpa: "3.6+",
    sat: "1350+",
    act: "30+",
    ap: "3 AP, баллы 4–5",
    english: "IELTS 6.5 / TOEFL 88",
    aid: "Merit-стипендии по результатам",
    tuition: "HK$175 000 / год",
    deadlines: [{ label: "International Application", date: "2027-01-05" }],
    programs: ["Medicine", "AI & Engineering", "Economics", "Translation"],
    overview: "Крупнейший кампус в Гонконге, сильные медицина и инженерия.",
    strategy: "Ценят исследовательский опыт и стабильно высокий GPA.",
  },
  {
    name: "City University of Hong Kong",
    country: "Hong Kong",
    city: "Kowloon Tong",
    qs: 62,
    gpa: "3.4+",
    sat: "1280+",
    act: "28+",
    ap: "2–3 AP",
    english: "IELTS 6.5 / TOEFL 79",
    aid: "Частичные стипендии для международных",
    tuition: "HK$145 000 / год",
    deadlines: [{ label: "Direct Application", date: "2027-01-12" }],
    programs: ["Creative Media", "Data Science", "Veterinary Medicine", "Business"],
    overview: "Городской кампус, практико-ориентированные программы и кооперация с индустрией.",
    strategy: "Хороший Match/Safety для средне-сильного профиля.",
  },
  {
    name: "Hong Kong Polytechnic University",
    country: "Hong Kong",
    city: "Hung Hom",
    qs: 57,
    gpa: "3.4+",
    sat: "1280+",
    act: "28+",
    ap: "2–3 AP",
    english: "IELTS 6.0 / TOEFL 80",
    aid: "Talent Scholarship Scheme",
    tuition: "HK$145 000 / год",
    deadlines: [{ label: "Main Round", date: "2027-01-15" }],
    programs: ["Design", "Hotel Management", "Civil Engineering", "Aviation"],
    overview: "Прикладной университет, сильнейшая школа дизайна и гостеприимства в Азии.",
    strategy: "Для дизайна нужно портфолио работ — начните собирать заранее.",
  },
  {
    name: "Hong Kong Baptist University",
    country: "Hong Kong",
    city: "Kowloon Tong",
    qs: 252,
    gpa: "3.2+",
    sat: "1200+",
    ap: "1–2 AP",
    english: "IELTS 6.0 / TOEFL 79",
    aid: "Частичные стипендии",
    tuition: "HK$145 000 / год",
    deadlines: [{ label: "Application Deadline", date: "2027-01-20" }],
    programs: ["Communication", "Chinese Medicine", "Business", "Music"],
    overview: "Либеральное образование, сильнейшая в Азии школа коммуникаций и журналистики.",
    strategy: "Safety-вариант с упором на креативные и гуманитарные направления.",
  },
  {
    name: "Lingnan University",
    country: "Hong Kong",
    city: "Tuen Mun",
    qs: 601,
    gpa: "3.0+",
    english: "IELTS 6.0 / TOEFL 79",
    aid: "Entrance scholarships",
    tuition: "HK$140 000 / год",
    deadlines: [{ label: "Application Deadline", date: "2027-02-01" }],
    programs: ["Liberal Arts", "Business", "Social Sciences"],
    overview: "Единственный университет свободных искусств Гонконга, маленькие классы.",
    strategy: "Надёжный Safety, ценят мотивационное письмо и интервью.",
  },
  {
    name: "Education University of Hong Kong",
    country: "Hong Kong",
    city: "Tai Po",
    qs: 451,
    gpa: "3.0+",
    english: "IELTS 6.0",
    aid: "Частичные стипендии",
    tuition: "HK$140 000 / год",
    deadlines: [{ label: "Application Deadline", date: "2027-02-01" }],
    programs: ["Education", "Psychology", "Language Studies"],
    overview: "Профильный педагогический университет с сильной практикой в школах.",
    strategy: "Волонтёрский опыт в преподавании — главный плюс заявки.",
  },
  {
    name: "Hong Kong Metropolitan University",
    country: "Hong Kong",
    city: "Ho Man Tin",
    qs: 801,
    gpa: "2.8+",
    english: "IELTS 6.0",
    aid: "Ограниченные стипендии",
    tuition: "HK$130 000 / год",
    deadlines: [{ label: "Rolling Admission", date: "2027-03-31" }],
    programs: ["Nursing", "Business", "Creative Arts"],
    overview: "Гибкие программы, включая вечерние и прикладные направления.",
    strategy: "Rolling-приём: чем раньше подадитесь, тем выше шанс.",
  },
  {
    name: "Hong Kong Shue Yan University",
    country: "Hong Kong",
    city: "North Point",
    qs: 1001,
    gpa: "2.8+",
    english: "IELTS 5.5",
    aid: "Частичные стипендии",
    tuition: "HK$120 000 / год",
    deadlines: [{ label: "Rolling Admission", date: "2027-04-30" }],
    programs: ["Journalism", "Counselling Psychology", "Law & Business"],
    overview: "Частный университет с маленькими группами и упором на социальные науки.",
    strategy: "Безопасный вариант при ограниченном бюджете.",
  },

  // ============ Kazakhstan ============
  {
    name: "Nazarbayev University",
    country: "Kazakhstan",
    city: "Астана",
    qs: 301,
    gpa: "4.5+ / 5.0",
    nuet: "NUET 120+ (Math + Critical Thinking)",
    sat: "1300+ (альтернатива NUET)",
    english: "IELTS 6.0+",
    aid: "Полный грант с стипендией для большинства студентов",
    tuition: "Покрывается грантом",
    deadlines: [
      { label: "Application Deadline", date: "2026-12-15" },
      { label: "NUET Exam", date: "2027-03-14" },
    ],
    programs: ["Computer Science", "Engineering", "Medicine", "Economics"],
    overview:
      "Англоязычный исследовательский университет мирового формата, партнёрства с Duke, Cambridge, NUS.",
    strategy: "Ключ — NUET. Готовьтесь к Math Level 2 и Critical Thinking минимум полгода.",
  },
  {
    name: "KIMEP University",
    country: "Kazakhstan",
    city: "Алматы",
    qs: 801,
    gpa: "4.0+",
    unt: "УНТ 110+",
    sat: "1150+",
    english: "IELTS 5.5+",
    aid: "Merit-стипендии до 100%",
    tuition: "~2 500 000 ₸ / год",
    deadlines: [{ label: "Приём документов", date: "2027-07-20" }],
    programs: ["Business Administration", "Law", "International Relations", "Finance"],
    overview: "Ведущий частный бизнес-вуз Казахстана с американской моделью обучения.",
    strategy: "Высокий балл IELTS напрямую конвертируется в размер стипендии.",
  },
  {
    name: "Satbayev University",
    country: "Kazakhstan",
    city: "Алматы",
    qs: 701,
    gpa: "3.8+",
    unt: "УНТ 100+ (профиль: физика/математика)",
    english: "IELTS 5.5",
    aid: "Государственные гранты",
    tuition: "~1 400 000 ₸ / год",
    deadlines: [
      { label: "Заявка на грант", date: "2027-07-13" },
      { label: "Зачисление", date: "2027-08-25" },
    ],
    programs: ["Нефтегазовое дело", "Геология", "IT-инженерия", "Металлургия"],
    overview: "Главный технический университет страны с сильными индустриальными связями.",
    strategy: "Профильный УНТ по физике и математике — основной фактор гранта.",
  },
  {
    name: "Al-Farabi Kazakh National University",
    country: "Kazakhstan",
    city: "Алматы",
    qs: 163,
    gpa: "3.8+",
    unt: "УНТ 105+",
    english: "IELTS 5.5",
    aid: "Госгранты, льготные квоты",
    tuition: "~1 200 000 ₸ / год",
    deadlines: [{ label: "Заявка на грант", date: "2027-07-13" }],
    programs: ["Медицина", "Международные отношения", "Физика", "Журналистика"],
    overview: "Крупнейший классический университет Казахстана, высокий рейтинг QS среди вузов СНГ.",
    strategy: "Олимпиады республиканского уровня дают гранты вне конкурса.",
  },
  {
    name: "SDU University",
    country: "Kazakhstan",
    city: "Каскелен",
    qs: 1001,
    gpa: "3.7+",
    unt: "УНТ 95+",
    english: "IELTS 5.5",
    aid: "Внутренние стипендии до 100%",
    tuition: "~1 500 000 ₸ / год",
    deadlines: [{ label: "Приём документов", date: "2027-07-25" }],
    programs: ["Computer Science", "Педагогика", "Инженерия", "Бизнес"],
    overview: "Англоязычный кампус, сильная IT-школа и обмены с турецкими вузами.",
    strategy: "Собственный вступительный экзамен — альтернатива низкому УНТ.",
  },
  {
    name: "Astana IT University",
    country: "Kazakhstan",
    city: "Астана",
    qs: 1001,
    gpa: "3.7+",
    unt: "УНТ 100+ (математика/информатика)",
    english: "IELTS 5.5",
    aid: "Гранты Digital Kazakhstan",
    tuition: "~2 000 000 ₸ / год",
    deadlines: [{ label: "Заявка на грант", date: "2027-07-13" }],
    programs: ["Software Engineering", "Cybersecurity", "Big Data", "Media Technologies"],
    overview: "Профильный IT-университет с проектным обучением и партнёрами из индустрии.",
    strategy: "Портфолио GitHub и хакатоны учитываются при отборе на стипендию.",
  },
  {
    name: "Kazakh-British Technical University",
    country: "Kazakhstan",
    city: "Алматы",
    qs: 1001,
    gpa: "3.8+",
    unt: "УНТ 105+",
    english: "IELTS 6.0",
    aid: "Корпоративные гранты (KMG, Chevron)",
    tuition: "~2 200 000 ₸ / год",
    deadlines: [{ label: "Приём документов", date: "2027-07-20" }],
    programs: ["Petroleum Engineering", "IT", "Финансы", "Химическая инженерия"],
    overview: "Обучение на английском по британским стандартам, сильное трудоустройство в нефтегаз.",
    strategy: "Корпоративные гранты требуют высокого IELTS и собеседования.",
  },
  {
    name: "Narxoz University",
    country: "Kazakhstan",
    city: "Алматы",
    qs: 1201,
    gpa: "3.5+",
    unt: "УНТ 90+",
    english: "IELTS 5.5",
    aid: "Скидки за академические успехи",
    tuition: "~1 300 000 ₸ / год",
    deadlines: [{ label: "Приём документов", date: "2027-07-25" }],
    programs: ["Экономика", "Финансы", "Право", "Data Analytics"],
    overview: "Экономический вуз с практикой в банках и консалтинге.",
    strategy: "Надёжный Safety для экономического направления.",
  },
  {
    name: "Kazakh National Medical University",
    country: "Kazakhstan",
    city: "Алматы",
    qs: 1001,
    gpa: "4.0+",
    unt: "УНТ 115+ (биология/химия)",
    english: "IELTS 5.5",
    aid: "Госгранты по медицинским квотам",
    tuition: "~1 800 000 ₸ / год",
    deadlines: [{ label: "Заявка на грант", date: "2027-07-13" }],
    programs: ["Общая медицина", "Стоматология", "Фармация", "Общественное здоровье"],
    overview: "Ведущий медицинский вуз страны с клинической базой в Алматы.",
    strategy: "Порог по профильным предметам УНТ выше, чем у большинства специальностей.",
  },
  {
    name: "Suleyman Demirel / Atyrau University of Oil and Gas",
    country: "Kazakhstan",
    city: "Атырау",
    qs: 1201,
    gpa: "3.5+",
    unt: "УНТ 90+",
    english: "IELTS 5.5",
    aid: "Гранты от нефтяных компаний региона",
    tuition: "~1 100 000 ₸ / год",
    deadlines: [{ label: "Приём документов", date: "2027-07-25" }],
    programs: ["Нефтегазовое дело", "Автоматизация", "Экология", "Логистика"],
    overview: "Региональный отраслевой вуз с прямыми стажировками в нефтяных компаниях.",
    strategy: "Целевые направления от работодателей дают льготный приём.",
  },

  // ============ Europe ============
  {
    name: "University of Oxford",
    country: "Europe",
    city: "Oxford, UK",
    qs: 3,
    gpa: "A*A*A равнозначно",
    ap: "5 AP с баллами 5 (профильные)",
    sat: "1500+",
    english: "IELTS 7.5 (7.0 в каждой секции)",
    aid: "Reach Oxford Scholarship для международных",
    tuition: "£39 000 / год",
    deadlines: [{ label: "UCAS Oxbridge Deadline", date: "2026-10-15" }],
    programs: ["PPE", "Mathematics & CS", "Medicine", "Law"],
    overview: "Тьюториальная система, колледжи, самый ранний дедлайн среди всех вузов Европы.",
    strategy: "Нужны вступительный тест (MAT/TSA/LNAT) и интервью — готовьтесь с весны.",
  },
  {
    name: "University of Cambridge",
    country: "Europe",
    city: "Cambridge, UK",
    qs: 5,
    gpa: "A*A*A равнозначно",
    ap: "5 AP с баллами 5",
    sat: "1500+",
    english: "IELTS 7.5",
    aid: "Cambridge Trust Scholarships",
    tuition: "£40 000 / год",
    deadlines: [{ label: "UCAS Oxbridge Deadline", date: "2026-10-15" }],
    programs: ["Natural Sciences", "Engineering", "Economics", "Computer Science"],
    overview: "Сильнейшие естественные науки, supervision-формат по 2–3 студента.",
    strategy: "Admissions Assessment + интервью. Глубина по одному предмету важнее широты.",
  },
  {
    name: "ETH Zürich",
    country: "Europe",
    city: "Zürich, Switzerland",
    qs: 7,
    gpa: "4.5+ / 5.0",
    ap: "AP Calculus BC, Physics C, Chemistry — 5",
    english: "IELTS 7.0 или немецкий C1",
    aid: "Excellence Scholarship (ESOP)",
    tuition: "CHF 1 600 / год — почти бесплатно",
    deadlines: [{ label: "Application Deadline", date: "2027-04-30" }],
    programs: ["Computer Science", "Mechanical Engineering", "Physics", "Architecture"],
    overview:
      "Лучший технический университет континентальной Европы при символической стоимости обучения.",
    strategy: "Бакалавриат преимущественно на немецком; либо сдавайте вступительный экзамен.",
  },
  {
    name: "Imperial College London",
    country: "Europe",
    city: "London, UK",
    qs: 2,
    gpa: "A*A*A",
    ap: "5 AP STEM с баллами 5",
    sat: "1500+",
    english: "IELTS 7.0",
    aid: "President's Scholarships",
    tuition: "£40 000 / год",
    deadlines: [{ label: "UCAS Deadline", date: "2027-01-14" }],
    programs: ["Medicine", "Computing", "Aeronautics", "Business"],
    overview: "Чисто STEM-университет №1 в Великобритании по инженерии и медицине.",
    strategy: "Personal statement строго про предмет — никакой «широты интересов».",
  },
  {
    name: "Technical University of Munich",
    country: "Europe",
    city: "München, Germany",
    qs: 28,
    gpa: "4.3+ / 5.0",
    ap: "4+ AP STEM",
    english: "IELTS 6.5 или немецкий B2/C1",
    aid: "Обучение почти бесплатно + Deutschlandstipendium",
    tuition: "€300 / семестр (сборы)",
    deadlines: [
      { label: "Winter Intake", date: "2027-05-31" },
      { label: "Summer Intake", date: "2027-01-15" },
    ],
    programs: ["Informatics", "Mechanical Engineering", "Management & Technology", "Physics"],
    overview: "Ведущий немецкий технический вуз, сильные связи с BMW, Siemens, Airbus.",
    strategy: "Может потребоваться Studienkolleg — уточните признание вашего аттестата.",
  },
  {
    name: "Delft University of Technology",
    country: "Europe",
    city: "Delft, Netherlands",
    qs: 49,
    gpa: "4.2+ / 5.0",
    ap: "AP Calculus BC + Physics C",
    english: "IELTS 6.5 / TOEFL 90",
    aid: "Justus & Louise van Effen Scholarship",
    tuition: "€20 000 / год для не-ЕС",
    deadlines: [{ label: "Numerus Fixus Deadline", date: "2027-01-15" }],
    programs: ["Aerospace Engineering", "Architecture", "Applied Physics", "Industrial Design"],
    overview: "Лучший инженерный вуз Нидерландов, англоязычные программы, проектное обучение.",
    strategy: "Numerus fixus — ограниченный набор, подавайтесь строго к 15 января.",
  },
  {
    name: "University of Amsterdam",
    country: "Europe",
    city: "Amsterdam, Netherlands",
    qs: 53,
    gpa: "4.0+",
    ap: "3–4 AP",
    english: "IELTS 6.5",
    aid: "Amsterdam Excellence Scholarship",
    tuition: "€15 000 / год для не-ЕС",
    deadlines: [{ label: "International Deadline", date: "2027-04-01" }],
    programs: ["PPLE", "Data Science", "Psychology", "Communication Science"],
    overview: "Крупнейший исследовательский университет Нидерландов, много англоязычных программ.",
    strategy: "Мотивационное письмо и matching-процедура важнее тестовых баллов.",
  },
  {
    name: "Sciences Po",
    country: "Europe",
    city: "Paris, France",
    qs: 319,
    gpa: "4.0+",
    ap: "AP History, Government, Economics",
    english: "IELTS 7.0 (+ французский для части кампусов)",
    aid: "Émile Boutmy Scholarship для международных",
    tuition: "€0–19 000 / год по доходу семьи",
    deadlines: [{ label: "International Admission", date: "2027-02-26" }],
    programs: ["Political Science", "Economics & Society", "Law", "Middle East Studies"],
    overview: "Главная школа политики и международных отношений Европы, третий год за рубежом.",
    strategy: "Ключ — видеоинтервью и эссе о гражданской позиции.",
  },
  {
    name: "Bocconi University",
    country: "Europe",
    city: "Milano, Italy",
    qs: 122,
    gpa: "4.2+",
    sat: "1350+",
    ap: "AP Calculus, Economics",
    english: "IELTS 6.5 / TOEFL 88",
    aid: "Merit-стипендии до полного покрытия",
    tuition: "€16 000 / год",
    deadlines: [
      { label: "Early Session", date: "2026-10-22" },
      { label: "Winter Session", date: "2027-01-14" },
    ],
    programs: ["Economics & Finance", "International Economics", "Data Science", "Management"],
    overview: "Ведущая бизнес-школа континентальной Европы с прямым выходом в финансы Лондона.",
    strategy: "Ранняя сессия даёт лучший доступ к стипендиям — подавайтесь в октябре.",
  },
  {
    name: "KU Leuven",
    country: "Europe",
    city: "Leuven, Belgium",
    qs: 61,
    gpa: "3.8+",
    ap: "3 AP",
    english: "IELTS 6.5",
    aid: "Science@Leuven Scholarship",
    tuition: "€6 000 / год для не-ЕС",
    deadlines: [{ label: "International Deadline", date: "2027-03-01" }],
    programs: ["Engineering", "Biomedical Sciences", "Business", "Philosophy"],
    overview: "Старейший университет Бельгии, топ по инновациям в Европе, доступная стоимость.",
    strategy: "Отличный Match при ограниченном бюджете и сильной академике.",
  },
];

export const UNIVERSITIES: University[] = RAW.map((u, i) => ({
  ...u,
  id: u.name.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
  photos: photos(i),
}));

export const COUNTRY_LIST: Country[] = ["USA", "Hong Kong", "Kazakhstan", "Europe"];
